version: "2"

services:
  order-service:
    image: gramman75/order-service:1.0
    container_name: order-service
    environment:
      spring.rabbitmq.host: rabbitmq
      spring.datasource.url: jdbc:mariadb://mariadb:3306/orderdb
      spring.datasource.username: root
      spring.datasource.password: mariadb
      spring.zipkin.base-url: http://zipkin:9411
      spring.cloud.config.uri: http://config-service:8888
      eureka.client.service-url.defaultZone: http://discovery-service:8761/eureka
    networks:
      - my-network

networks:
  my-network:
    name: ecommerce-network