spring:
  profiles:
    active: @activatedProperties@

  application:
    name: order-service

greeting:
  message: Welcome to the E-Commerce


management:
  endpoints:
    web:
      exposure:
        include: health, refresh, beans, busrefresh, info, prometheus, metrics